version: '3.8'

services:
  frontend:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - project_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - '8000'
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
